### ISSUE TITLE
skippy fails when trying to load custom commands with missing dependencies

### ISSUE THREAD

**Issue by thomthom** [thomthom/skippy#2]
Should add a load guard for each file.

```
C:\Users\tthomas2\SourceTree\SUbD (dev-cleanup) (subd@2.1.0)
λ skippy
C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- chronic_duration (LoadError)
        from C:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Users/tthomas2/SourceTree/SUbD/skippy/commands/localize.rb:1:in `load_thorfile'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/util.rb:156:in `class_eval'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/util.rb:156:in `load_thorfile'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/skippy-0.2.0.a/lib/skippy/cli.rb:115:in `block in initialize_thorfiles'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/skippy-0.2.0.a/lib/skippy/project.rb:60:in `block in command_files'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/skippy-0.2.0.a/lib/skippy/project.rb:59:in `glob'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/skippy-0.2.0.a/lib/skippy/project.rb:59:in `command_files'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/skippy-0.2.0.a/lib/skippy/cli.rb:113:in `initialize_thorfiles'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/skippy-0.2.0.a/lib/skippy/cli.rb:79:in `list'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/skippy-0.2.0.a/app/boot.rb:40:in `<top (required)>'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/skippy-0.2.0.a/exe/skippy:2:in `require_relative'
        from C:/Ruby23/lib/ruby/gems/2.3.0/gems/skippy-0.2.0.a/exe/skippy:2:in `<top (required)>'
        from C:/Ruby23/bin/skippy:22:in `load'
        from C:/Ruby23/bin/skippy:22:in `<main>'
```

**Comment by thomthom** [comment]
Fixed in bae7fc2f4c90e8b34864b3839d3c85f6344ac819
