### ISSUE TITLE
`lib:use` fails with `undefined method `copy' for File:Class`

### ISSUE THREAD

**Issue by thomthom** [thomthom/skippy#30]
```
PS C:\Users\Thomas\SourceTree\TrueBend> skippy lib:use heimdallr/error-reporter
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/skippy-0.4.1.a/lib/skippy/module_manager.rb:153:in `copy_file': undefined method `copy' for File:Class (NoMethodError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/skippy-0.4.1.a/lib/skippy/module_manager.rb:138:in `block in copy_directory'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/skippy-0.4.1.a/lib/skippy/module_manager.rb:133:in `glob'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/skippy-0.4.1.a/lib/skippy/module_manager.rb:133:in `copy_directory'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/skippy-0.4.1.a/lib/skippy/module_manager.rb:126:in `copy_module'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/skippy-0.4.1.a/lib/skippy/module_manager.rb:56:in `use'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/skippy-0.4.1.a/app/commands/lib.rb:62:in `use'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/skippy-0.4.1.a/lib/skippy/cli.rb:70:in `method_missing'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/command.rb:29:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/command.rb:128:in `run'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/skippy-0.4.1.a/app/boot.rb:40:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/skippy-0.4.1.a/exe/skippy:2:in `require_relative'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/skippy-0.4.1.a/exe/skippy:2:in `<top (required)>'
        from C:/Ruby22-x64/bin/skippy:23:in `load'
        from C:/Ruby22-x64/bin/skippy:23:in `<main>'
```

**Comment by thomthom** [comment]
Missing tests for this scenario. (module include non-ruby files).
